import { FREE_LOCAL_HELP, PARTIAL_COURSE_LIST, SELF_STUDY_CAVEAT } from "@/content/bridge";
import { claimFor, reviewBy, type Claimed, type ClaimKey, type Label } from "@/content/claims";
import { occupations as analysisOccupations } from "@/content/occupations";
import { cardFor, destinationCardFor, type Card, type RouteCard } from "@/content/screen/card";
import { occupationBySoc, workforceOccupations } from "@/content/workforce";

/**
 * The back artifact. One row per published sentence.
 *
 * Generated by walking the copy layer rather than maintained by hand, because a
 * hand-maintained appendix drifts from the screen the first time someone edits a
 * sentence — and an appendix that disagrees with the screen is worse than none.
 *
 * A sentence is anything the copy layer emits. Headings, link labels and the
 * chrome around them are not sentences and have no rows; they assert nothing.
 */

export type AppendixRow = {
  /** Card, scope and slot: `43-4051 / route-1 / training`. */
  screenId: string;
  sentence: string;
  label: Label;
  basis: string;
  url: string;
  retrieved: string;
  priceStatus: string;
  /** Named gate, or `none seen`. */
  gateVisible: string;
  /** A gate suspected but not in the Skills file. Always UNVERIFIED. */
  gateUnmeasured: string;
  reviewBy: string;
};

/** One sentence per row, so a block of prose becomes several rows. */
function sentencesOf(text: string): string[] {
  return text
    .split(/(?<=[.?!])\s+(?=[A-Z“"])/)
    .map((s) => s.trim())
    .filter(Boolean);
}

function rows(screenId: string, claimed: Claimed | Claimed[] | null | undefined): AppendixRow[] {
  if (!claimed) return [];
  const list = Array.isArray(claimed) ? claimed : [claimed];
  return list.flatMap((c) =>
    sentencesOf(c.text).map((sentence) => row(screenId, sentence, c.claim)),
  );
}

function row(screenId: string, sentence: string, key: ClaimKey): AppendixRow {
  const claim = claimFor(key);
  const unmeasured = claim.label === "UNVERIFIED";
  return {
    screenId,
    sentence,
    label: claim.label,
    basis: claim.basis,
    url: claim.url ?? "",
    retrieved: claim.retrieved,
    priceStatus: claim.priceStatus,
    gateVisible: screenId.endsWith("/ gate") && !unmeasured ? claim.basis : "none seen",
    gateUnmeasured: unmeasured ? claim.basis : "",
    reviewBy: reviewBy(key),
  };
}

function routeRows(soc: string, route: RouteCard, index: number): AppendixRow[] {
  const at = `${soc} / route-${index + 1}`;
  const { bridge } = route;

  return [
    ...rows(`${at} / pay`, route.line),
    ...rows(`${at} / different`, route.different),
    ...rows(`${at} / summary`, route.summary),
    ...rows(`${at} / ai-use`, route.aiUse),
    ...rows(`${at} / gate`, bridge.gate.need),
    ...bridge.training.flatMap(({ training }) => [
      ...rows(`${at} / training`, { text: training.detail, claim: training.claim }),
      ...training.options.flatMap((o) =>
        rows(`${at} / training-option`, {
          text: `${o.name} — ${o.provider} · ${o.cost} · ${o.scope}`,
          claim: o.claim,
        }),
      ),
      ...training.selfStudy.flatMap((o) =>
        rows(`${at} / free-study`, {
          text: `${o.name} — ${o.provider}. ${o.access}. ${o.covers}.`,
          claim: o.claim,
        }),
      ),
      ...(training.selfStudy.length > 0
        ? rows(`${at} / free-study-caveat`, SELF_STUDY_CAVEAT)
        : []),
    ]),
  ];
}

export function rowsForCard(card: Card): AppendixRow[] {
  const { soc } = card;
  return [
    ...rows(`${soc} / header / scale`, card.scale),
    ...rows(`${soc} / header / ai-use`, card.aiUse),
    ...rows(`${soc} / routes / intro`, card.routesIntro),
    ...rows(`${soc} / routes / none`, card.noRoutes),
    ...card.routes.flatMap((r, i) => routeRows(soc, r, i)),
    ...rows(`${soc} / stay / does`, card.stay.does),
    ...rows(`${soc} / stay / evidence`, card.stay.evidence),
    ...rows(`${soc} / stay / check`, card.stay.mustCheck),
    ...rows(`${soc} / stay / decides`, card.stay.whoDecides),
    ...rows(`${soc} / help / library`, {
      text: FREE_LOCAL_HELP.card.text,
      claim: FREE_LOCAL_HELP.card.claim,
    }),
    ...rows(`${soc} / help / board`, {
      text: FREE_LOCAL_HELP.board.text,
      claim: FREE_LOCAL_HELP.board.claim,
    }),
    ...rows(`${soc} / sources / partial-course-list`, PARTIAL_COURSE_LIST),
  ];
}

/**
 * `/job/$soc` also serves any occupation in the analysis file as a destination
 * page. Those are published screens with published sentences, including the one
 * that explains an occupation the exposure sample never saw, so they are walked
 * too rather than left as an unaudited back door.
 */
export function destinationRows(): AppendixRow[] {
  return analysisOccupations
    .filter((o) => occupationBySoc(o.code) === undefined)
    .flatMap((o) => {
      const card = destinationCardFor(o);
      return [
        ...rows(`${card.soc} / destination / lead`, card.lead),
        ...rows(`${card.soc} / destination / ai-use`, card.aiUse),
      ];
    });
}

export function buildAppendix(): AppendixRow[] {
  return [...workforceOccupations.flatMap((o) => rowsForCard(cardFor(o))), ...destinationRows()];
}

const COLUMNS: [keyof AppendixRow, string][] = [
  ["screenId", "screen_id"],
  ["sentence", "sentence"],
  ["label", "label"],
  ["basis", "basis"],
  ["url", "url"],
  ["retrieved", "retrieved"],
  ["priceStatus", "price_status"],
  ["gateVisible", "gate_visible"],
  ["gateUnmeasured", "gate_unmeasured"],
  ["reviewBy", "review_by"],
];

function csvCell(value: string): string {
  return /[",\n]/.test(value) ? `"${value.replaceAll('"', '""')}"` : value;
}

export function appendixCsv(rowsIn: AppendixRow[] = buildAppendix()): string {
  const header = COLUMNS.map(([, name]) => name).join(",");
  const body = rowsIn.map((r) => COLUMNS.map(([key]) => csvCell(r[key])).join(","));
  return [header, ...body].join("\n");
}
