import { bridgeFor, bridgeSummary, routeDuration, type Bridge } from "@/content/bridge";
import type { Claimed } from "@/content/claims";
import { inRoleFor, type InRole } from "@/content/inRole";
import { plainSkillList } from "@/content/skillWords";
import {
  routesOf,
  sortDestinations,
  type Destination,
  type WorkforceOccupation,
} from "@/content/workforce";
import { BAND_MEANING, exposureBand, DESTINATION_ONLY, EMPTY_ROUTES } from "@/lib/exposureBand";

/**
 * The sentences a job screen publishes, assembled away from the components that
 * render them.
 *
 * The point of the separation is the audit appendix: every sentence below is
 * reachable from `cardFor`, so the appendix can be generated by walking all 39
 * cards rather than by someone remembering to add a row. A sentence written
 * directly into JSX would be invisible to that walk, which is why numbers and
 * sourced claims are built here and the components render what they are given.
 *
 * Headings and link labels stay in the components. They assert nothing.
 */

export type Card = {
  soc: string;
  title: string;
  group: string;
  /** How many people, and what the pay figure is and is not. */
  scale: Claimed[];
  /** One sentence about AI use. Never the score. */
  aiUse: Claimed;
  /** Present when at least one route exists. */
  routesIntro: Claimed | null;
  routes: RouteCard[];
  /** Empty state B, present only when there are no routes at all. */
  noRoutes: Claimed | null;
  stay: InRole;
};

export type RouteCard = {
  soc: string;
  title: string;
  /** Pay, the gain over the origin, and how long — or that it is not a course. */
  line: Claimed[];
  /** What's different, in plain words. Absent where no gap was measured. */
  different: Claimed | null;
  /** Collapsed summary of the row, so it can be skipped without being opened. */
  summary: Claimed[];
  aiUse: Claimed | null;
  bridge: Bridge;
};

function usd(n: number): string {
  return n.toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  });
}

/**
 * Pay is two sentences, always. The published figure is an annual mean, so the
 * second sentence is what stops a reader treating it as what they would be paid.
 */
function paySentences(wage: number, lead: string): Claimed[] {
  return [
    { text: `${lead} ${usd(wage)} a year.`, claim: "oews.mean-wage" },
    {
      text: "That is an average across everyone doing this job here, so most people earn less than it.",
      claim: "oews.mean-not-median",
    },
  ];
}

function routeCard(d: Destination): RouteCard {
  const duration = routeDuration(d);
  const different = plainSkillList(d.build.map((s) => s.name));

  const line: Claimed[] = [
    { text: `Average pay ${usd(d.wage)} a year.`, claim: "oews.mean-wage" },
    ...(d.wageGain > 0
      ? [
          {
            text: `That is ${usd(d.wageGain)} a year more than this job.`,
            claim: "oews.wage-gain" as const,
          },
        ]
      : []),
    ...(duration ? [duration] : []),
  ];

  const band = exposureBand(d.exposure);

  return {
    soc: d.soc,
    title: d.title,
    line,
    different: different
      ? { text: `What's different: ${different}.`, claim: "onet.skill-gap" }
      : null,
    summary: bridgeSummary(bridgeFor(d), d.build.length),
    aiUse: d.exposure === 0 ? null : BAND_MEANING[band],
    bridge: bridgeFor(d),
  };
}

export function cardFor(job: WorkforceOccupation): Card {
  const routes = sortDestinations(routesOf(job));

  return {
    soc: job.soc,
    title: job.title,
    group: job.group,
    scale: [
      {
        text: `About ${job.employment.toLocaleString("en-US")} people do this job in Greater Richmond.`,
        claim: "oews.employment",
      },
      ...(job.wage != null ? paySentences(job.wage, "The average pay is") : []),
    ],
    aiUse: BAND_MEANING[exposureBand(job.exposure)],
    routesIntro:
      routes.length > 0
        ? {
            text:
              routes.length === 1
                ? "One other job on this map leads on from here. It pays more and uses AI less."
                : `${routes.length} other jobs on this map lead on from here. Each one pays more and uses AI less.`,
            claim: "onet.related",
          }
        : null,
    routes: routes.map(routeCard),
    noRoutes: routes.length === 0 ? EMPTY_ROUTES : null,
    stay: inRoleFor(job.soc),
  };
}

/** A job that appears on the map only as somewhere to go, not somewhere to start. */
export type DestinationCard = {
  soc: string;
  title: string;
  group: string;
  lead: Claimed;
  aiUse: Claimed;
};

export function destinationCardFor(job: {
  code: string;
  title: string;
  group: string;
  exposure: number;
}): DestinationCard {
  return {
    soc: job.code,
    title: job.title,
    group: job.group,
    lead: DESTINATION_ONLY,
    aiUse: BAND_MEANING[exposureBand(job.exposure)],
  };
}
